#!/usr/bin/env bash

X11_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/X11
SYS_RESOURCES=/etc/X11/xinit/.Xresources
SYS_MODMAP=/etc/X11/xinit/.Xmodmap
USER_RESOURCES=$HOME/.Xresources
USER_MODMAP=$X11_CONFIG_DIR/Xmodmap
USER_XINITRC=$X11_CONFIG_DIR/nvidia-xinitrc

# merge in defaults and keymaps
if [[ -f ${SYS_RESOURCES} ]]; then
    xrdb -merge ${SYS_RESOURCES}
fi

if [[ -f ${SYS_MODMAP} ]]; then
    xmodmap ${SYS_MODMAP}
fi

if [[ -f "$USER_RESOURCES" ]]; then
    xrdb -merge "$USER_RESOURCES"
fi

if [[ -f "$USER_MODMAP" ]]; then
    xmodmap "$USER_MODMAP"
fi

export LD_LIBRARY_PATH=/usr/lib/nvidia:/usr/lib:${LD_LIBRARY_PATH}

# load additional configs
if [[ -d /etc/X11/xinit/nvidia-xinitrc.d ]] ; then
    for f in /etc/X11/xinit/nvidia-xinitrc.d/?*.sh ; do
        [[ -x "$f" ]] && . "$f"
    done
    unset f
fi

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

if [[ -f "$USER_XINITRC" ]]; then
    sh ${USER_XINITRC} $*
else
    if [[ $# -gt 0 ]]; then
        sh -c "exec $*"
    fi
fi
